{
  "error": "{'message': \"Could not find the 'identification_confidence' column of 'card_detections' in the schema cache\", 'code': 'PGRST204', 'hint': None, 'details': None}",
  "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\mdand\\Projects\\project-arceus\\worker\\worker.py\", line 444, in main\n    pipeline_results = run_normalized_pipeline(supabase_client, job, yolo_model, hybrid_identifier)\n  File \"C:\\Users\\mdand\\Projects\\project-arceus\\worker\\worker.py\", line 341, in run_normalized_pipeline\n    raise e\n  File \"C:\\Users\\mdand\\Projects\\project-arceus\\worker\\worker.py\", line 291, in run_normalized_pipeline\n    detection_response = supabase_client.from_(\"card_detections\").insert(detection_data).execute()\n  File \"C:\\Users\\mdand\\Projects\\project-arceus\\.venv\\Lib\\site-packages\\postgrest\\_sync\\request_builder.py\", line 78, in execute\n    raise APIError(dict(json_obj))\npostgrest.exceptions.APIError: {'message': \"Could not find the 'identification_confidence' column of 'card_detections' in the schema cache\", 'code': 'PGRST204', 'hint': None, 'details': None}\n"
}